version: "3.5"
services:
  mysql:
    image: mysql:8.0
    container_name: maeil_mail-mysql
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .mysql.env
    volumes:
      - ./.db/mysql:/var/lib/mysql
      - ./.db/initdb.d:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
